Bundles\StoreBundle\Entity\Dam:
    type: entity
    table: null
    repositoryClass: Bundles\StoreBundle\Entity\DamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        status:
            type: boolean
        travelId:
            type: integer

    lifecycleCallbacks: {  }
