Bundles\StoreBundle\Entity\Photo:
    type: entity
    table: null
    repositoryClass: Bundles\StoreBundle\Entity\PhotoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        adress:
            type: string
            length: 255
        damId:
            type: integer
        travelId:
            type: integer
    manyToOne:
         dam:
           targetEntity: Dam
           inversedBy: photo
           joinColumn:
             name: damId
             referencedColumnName: id
         travel:
           targetEntity: Travel
           inversedBy: photo
           joinColumn:
             name: travelId
             referencedColumnName: id
    lifecycleCallbacks: {  }
