Bundles\StoreBundle\Entity\Travel:
    type: entity
    table: null
    repositoryClass: Bundles\StoreBundle\Entity\TravelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        data:
            type: datetime
    oneToMany:
          dam:
              targetEntity: Dam
              mappedBy: travel
          photo:
              targetEntity: Photo
              mappedBy: travel
    manyToMany:
        user:
          targetEntity: User
          inversedBy: travel
          joinTable:
            name: user_to_travel
            joinColumns:
                travelId:
                    referencedColumnName: id
            inverseJoinColumns:
                userId:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
