Bundles\StoreBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Bundles\StoreBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

        fio:
            type: string
            length: 255
            nullable: TRUE
        tel:
            type: string
            length: 255
            nullable: TRUE

    manyToMany:
         travel:
             targetEntity: Travel
             mappedBy: user
         dam:
             targetEntity: Dam
             mappedBy: user
    lifecycleCallbacks: {  }
