<?php

namespace Bundles\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeoTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoTagRepository extends EntityRepository
{
}
